### ISSUE TITLE
Uncaught TypeError: Cannot read property 'cljs$core$IFn$_invoke$arity$1' of null

### ISSUE THREAD

**Issue by mauricioszabo** [mauricioszabo/atom-chlorine#134]
[Enter steps to reproduce:]

1. Show doc for var on `s/keys` on ClojureScript, with the following code: `(s/keys :)`

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Ubuntu 18.04.3
**Thrown From**: [chlorine](https://github.com/mauricioszabo/atom-chlorine) package 0.3.8

### Stack Trace

Uncaught TypeError: Cannot read property 'cljs$core$IFn$_invoke$arity$1' of null

```
At /home/mauricio/.atom/packages/chlorine/lib/js/cljs-runtime/clojure.zip.js:54

TypeError: Cannot read property 'cljs$core$IFn$_invoke$arity$1' of null
    at /packages/chlorine/lib/js/cljs-runtime/clojure.zip.js:54:13)
    at /packages/chlorine/lib/js/cljs-runtime/repl_tooling.editor_helpers.js:1405:146
    at /packages/chlorine/lib/js/cljs-runtime/repl_tooling.editor_helpers.js:1406:3)
    at /packages/chlorine/lib/js/cljs-runtime/repl_tooling.editor_helpers.js:1430:52)
    at /packages/chlorine/lib/js/cljs-runtime/repl_tooling.editor_integration.doc.js:128:46)
    at /packages/chlorine/lib/js/cljs-runtime/repl_tooling.editor_integration.connection.js:119:44
    at /packages/chlorine/lib/js/cljs-runtime/repl_tooling.editor_integration.connection.js:52:105)
    at /packages/chlorine/lib/js/cljs-runtime/repl_tooling.editor_integration.connection.js:117:51
    at HTMLElement.chlorine.repl.decide_command (/packages/chlorine/lib/js/cljs-runtime/chlorine.repl.js:55:99)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:349392)
    at KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:1252536)
    at KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/static/<embedded>:11:1248670)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/static/<embedded>:11:284598)
```

### Commands

```
     -1:03.2.0 editor:select-to-end-of-line (input.hidden-input)
     -1:03.0 core:select-left (input.hidden-input)
     -1:01.1.0 core:move-down (input.hidden-input)
     -1:01.1.0 autocomplete-plus:confirm (input.hidden-input)
     -1:00.5.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -1:00.3.0 lisp-paredit:newline (input.hidden-input)
     -0:45.5.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
     -0:44.9.0 inline-results:clear-all (input.hidden-input)
     -0:44 vim-mode-plus:insert-after (input.hidden-input)
     -0:17.4.0 core:move-left (input.hidden-input)
  2x -0:17.2.0 core:select-right (input.hidden-input)
     -0:16 core:backspace (input.hidden-input)
     -0:14.2.0 autocomplete-plus:confirm (input.hidden-input)
     -0:10.3.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
  2x -0:10.2.0 vim-mode-plus:move-left (input.hidden-input)
  2x -0:09.9.0 chlorine:doc-for-var (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ide-ui 0.13.0 
atom-limelight 0.1.3 
chlorine 0.3.8 
chlorine-tests 0.0.0 
clippy 0.5.0 
everything 0.3.0 
ex-mode 0.18.0 
hey-pane 1.2.0 
ide-php 0.7.18 
ink 0.11.6 
last-cursor-position 0.9.3 
linter 2.3.1 
linter-joker 4.1.0 
lisp-paredit 0.6.0 
parinfer 1.23.0 
platformio-ide-terminal 2.10.0 
set-syntax 0.4.0 
simple-align 0.2.0 
simple-git 0.2.0 
sync-settings 0.8.6 
tmux-terminal 0.0.1 
vim-mode-plus 1.36.2 
```

**Comment by mauricioszabo** [comment]
Can't reproduce it anymore. Probably fixed on `v0.10.0`
