### ISSUE TITLE
Uncaught Error: Index 30 out of bounds [0,29]

### ISSUE THREAD

**Issue by j0ni** [mauricioszabo/atom-chlorine#150]
[Enter steps to reproduce:]

1. Select the whole of the buffer
2. Execute "Chlorine: Evaluate Selection"
3. Boom

**Atom**: 1.44.0 x64
**Electron**: 4.2.12
**OS**: "Arch Linux"
**Thrown From**: [chlorine](https://github.com/mauricioszabo/atom-chlorine) package 0.4.5

### Stack Trace

Uncaught Error: Index 30 out of bounds [0,29]

```
At /home/joni/.atom/packages/chlorine/lib/cmds.js:307

Error: Index 30 out of bounds [0,29]
    at ci.g.vc (/packages/chlorine/lib/cmds.js:307:65)
    at ci.g.G (/packages/chlorine/lib/cmds.js:309:266)
    at Function.P.g (/packages/chlorine/lib/cmds.js:104:59)
    at Function.Bh.g (/packages/chlorine/lib/cmds.js:278:99)
    at U_ (/packages/chlorine/lib/cmds.js:1098:152)
    at /packages/chlorine/lib/cmds.js:1491:289
    at P4 (/packages/chlorine/lib/cmds.js:1490:952)
    at /packages/chlorine/lib/cmds.js:1491:241
    at O4 (/packages/chlorine/lib/cmds.js:1490:818)
    at /packages/chlorine/lib/cmds.js:1491:160)
    at /packages/chlorine/lib/cmds.js:1492:509
    at /packages/chlorine/lib/cmds.js:1511:137)
    at CommandRegistry.handleCommandEvent (/usr/lib/atom/src/command-registry.js:405:43)
    at Object.didConfirmSelection (/usr/lib/atom/node_modules/command-palette/lib/command-palette-view.js:152:29)
    at SelectListView.confirmSelection (/usr/lib/atom/node_modules/atom-select-list/src/select-list-view.js:400:20)
    at HTMLDivElement.core:confirm (/usr/lib/atom/node_modules/atom-select-list/src/select-list-view.js:105:14)
    at CommandRegistry.handleCommandEvent (/usr/lib/atom/src/command-registry.js:405:43)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/lib/atom/node_modules/atom-keymap/lib/keymap-manager.js:617:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/lib/atom/node_modules/atom-keymap/lib/keymap-manager.js:408:22)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/lib/atom/src/window-event-handler.js:153:34)
```

### Commands

```
     -0:39.3.0 core:cancel (input.hidden-input)
  4x -0:38.5.0 atomic-emacs:previous-line (input.hidden-input)
  3x -0:34.4.0 core:page-up (input.hidden-input)
     -0:33.5.0 atomic-emacs:previous-line (input.hidden-input)
     -0:32.4.0 atomic-emacs:set-mark (input.hidden-input)
  5x -0:31.2.0 core:page-down (input.hidden-input)
     -0:29 atomic-emacs:copy-region-as-kill (input.hidden-input)
  6x -0:25.6.0 core:page-up (input.hidden-input)
     -0:24.4.0 atomic-emacs:set-mark (input.hidden-input)
  4x -0:23.4.0 core:page-down (input.hidden-input)
     -0:21 command-palette:toggle (input.hidden-input)
     -0:18.1.0 core:confirm (input.hidden-input)
     -0:18.1.0 chlorine:evaluate-block (input.hidden-input)
     -0:12.6.0 command-palette:toggle (input.hidden-input)
     -0:10 core:confirm (input.hidden-input)
     -0:09.9.0 chlorine:evaluate-selection (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
atom-beautify 0.33.4 
atom-haskell 0.4.0 
atom-haskell-hie 0.5.0 
atom-ide-ui 0.13.0 
atomic-emacs 0.15.0 
autocomplete-haskell 1.0.1 
busy-signal 2.0.1 
chlorine 0.4.5 
clojure-lsp-adapter 0.1.0 
haskell-ghc-mod 2.2.5 
haskell-pointfree 0.2.0 
haskell-scry 1.0.9 
hasklig 0.4.0 
highlight-selected 0.17.0 
Hydrogen 2.13.1 
ide-haskell 2.4.1 
ide-haskell-cabal 2.3.0 
ide-haskell-hasktags 0.0.16 
ide-haskell-hoogle 0.1.2 
ide-haskell-repl 0.9.0 
ide-rust 0.21.2 
ink 0.11.8 
intentions 1.1.5 
language-haskell 1.19.4 
language-haskell-scoped 0.1.1 
languageserver-rust 0.3.0 
linter 2.3.1 
linter-joker 4.1.0 
linter-ui-default 1.8.1 
lisp-paredit 0.6.0 
nord-atom-syntax 0.10.0 
nord-atom-ui 0.12.0 
proto-repl 1.4.24 
proto-repl-charts 0.4.1 
proto-repl-sayid 0.1.4 
rainbow-delimiters 2.1.2 
rustfmt 0.1.3 
tool-bar 1.2.0 
Zen 0.18.0 
```

**Comment by mauricioszabo** [comment]
Thanks for the issue! In the meantime, you can save the file and run "Load file" from the command palette instead.
