### ISSUE TITLE
Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not ...

### ISSUE THREAD

**Issue by mauricioszabo** [mauricioszabo/atom-chlorine#151]
Sometimes, when evaluating code from the Shadow-CLJS REPL that resolves to a promise, this error is issued. 

The problematic part is the "ink results" block result.

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Ubuntu 18.04.4
**Thrown From**: [chlorine](https://github.com/mauricioszabo/atom-chlorine) package 0.4.5

### Stack Trace

Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

```
At /home/mauricio/.atom/packages/chlorine/node_modules/react-dom/cjs/react-dom.production.min.js:121

Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Xi (/packages/chlorine/node_modules/react-dom/cjs/react-dom.production.min.js:205:80)
    at ik (/packages/chlorine/node_modules/react-dom/cjs/react-dom.production.min.js:249:52)
    at exports.unstable_runWithPriority (/packages/chlorine/node_modules/scheduler/cjs/scheduler.production.min.js:18:437)
    at fg (/packages/chlorine/node_modules/react-dom/cjs/react-dom.production.min.js:120:325)
    at Yj (/packages/chlorine/node_modules/react-dom/cjs/react-dom.production.min.js:244:437)
    at Lj (/packages/chlorine/node_modules/react-dom/cjs/react-dom.production.min.js:223:420)
    at /packages/chlorine/node_modules/react-dom/cjs/react-dom.production.min.js:121:115
    at exports.unstable_runWithPriority (/packages/chlorine/node_modules/scheduler/cjs/scheduler.production.min.js:18:437)
    at fg (/packages/chlorine/node_modules/react-dom/cjs/react-dom.production.min.js:120:325)
    at ig (/packages/chlorine/node_modules/react-dom/cjs/react-dom.production.min.js:121:61)
    at jg (/packages/chlorine/node_modules/react-dom/cjs/react-dom.production.min.js:120:496)
    at Rg (/packages/chlorine/node_modules/react-dom/cjs/react-dom.production.min.js:214:156)
    at Object.enqueueForceUpdate (/packages/chlorine/node_modules/react-dom/cjs/react-dom.production.min.js:134:76)
    at Object.E.forceUpdate (/packages/chlorine/node_modules/react/cjs/react.production.min.js:13:318)
    at /packages/chlorine/lib/js/cljs-runtime/reagent.impl.batching.js:52:25)
    at reagent.impl.batching.RenderQueue.flush_queues (/packages/chlorine/lib/js/cljs-runtime/reagent.impl.batching.js:146:23)
    at reagent.impl.batching.RenderQueue.run_queues (/packages/chlorine/lib/js/cljs-runtime/reagent.impl.batching.js:157:14)
    at G__29472 (/packages/chlorine/lib/js/cljs-runtime/reagent.impl.batching.js:127:14)
```

### Commands

```
     -1:31 vim-mode-plus:activate-normal-mode (input.hidden-input)
  2x -1:31 vim-mode-plus:move-down (input.hidden-input)
     -1:30.5.0 vim-mode-plus:move-to-beginning-of-line (input.hidden-input)
  2x -1:30.3.0 vim-mode-plus:move-right (input.hidden-input)
     -1:29.9.0 chlorine:evaluate-top-block (input.hidden-input)
     -1:26 vim-mode-plus:move-to-last-character-of-line (input.hidden-input)
  6x -1:25.5.0 vim-mode-plus:move-up (input.hidden-input)
  3x -1:24.4.0 lisp-paredit:up-sexp (input.hidden-input)
     -1:23.8.0 vim-mode-plus:move-up (input.hidden-input)
  2x -1:23.3.0 chlorine:evaluate-block (input.hidden-input)
     -0:31.6.0 chlorine:clear-console (input.hidden-input)
     -0:31.3.0 inline-results:clear-all (input.hidden-input)
     -0:30.9.0 chlorine:evaluate-top-block (input.hidden-input)
  4x -0:02.9.0 vim-mode-plus:move-up (input.hidden-input)
     -0:02.2.0 vim-mode-plus:move-right (input.hidden-input)
     -0:01.8.0 chlorine:evaluate-top-block (input.hidden-input)
```

### Non-Core Packages

```
chlorine 0.4.5 
clippy 0.5.0 
everything 0.3.0 
ex-mode 0.18.0 
hey-pane 1.2.0 
ink 0.11.6 
last-cursor-position 0.9.3 
lisp-paredit 0.6.0 
parinfer 1.23.0 
platformio-ide-terminal 2.10.0 
set-syntax 0.4.0 
simple-align 0.2.0 
simple-git 0.2.0 
sync-settings 0.8.6 
tmux-terminal 0.0.1 
vim-mode-plus 1.36.2 
```

**Comment by mauricioszabo** [comment]
Probably fixed on 0.7.2
