### ISSUE TITLE
Uncaught Error: No protocol method IDeref.-deref defined for type null: 

### ISSUE THREAD

**Issue by SarmBoJim** [mauricioszabo/atom-chlorine#219]
[Enter steps to reproduce:]

1. Connect to socket REPL
2. Enter the code `(read)` in my core.clj file and evaluate it.
3. A spinning cog then appears on the line below.
4. I then disconnect the socket REPL and it throws the error.

**Atom**: 1.51.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [chlorine](https://github.com/mauricioszabo/atom-chlorine) package 0.9.4

### Stack Trace

Uncaught Error: No protocol method IDeref.-deref defined for type null: 

```
At C:\Users\celap\.atom\packages\chlorine\lib\cmds.js:460

Error: No protocol method IDeref.-deref defined for type null: 
    at ic (/packages/chlorine/lib/cmds.js:440:279)
    at /packages/chlorine/lib/cmds.js:460:438)
    at J2 (/packages/chlorine/lib/cmds.js:2646:198)
    at /packages/chlorine/lib/cmds.js:2933:280
    at /packages/chlorine/lib/cmds.js:2686:465
    at f3 (/packages/chlorine/lib/cmds.js:2665:331)
    at Sva (/packages/chlorine/lib/cmds.js:2667:304)
    at /packages/chlorine/lib/cmds.js:2670:196
    at uwa (/packages/chlorine/lib/cmds.js:2719:456)
    at wwa (/packages/chlorine/lib/cmds.js:2721:330)
    at /packages/chlorine/lib/cmds.js:2721:475
    at pj.k.ee (/packages/chlorine/lib/cmds.js:712:431)
    at tj (/packages/chlorine/lib/cmds.js:714:349)
    at Function.vj.h (/packages/chlorine/lib/cmds.js:717:206)
    at /packages/chlorine/lib/cmds.js:2725:226)
    at Socket.emit (events.js:194:13)
    at addChunk (_stream_readable.js:296:12)
    at readableAddChunk (_stream_readable.js:277:11)
    at Socket.Readable.push (_stream_readable.js:232:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:165:17)
```

### Commands

```
     -1:17.9.0 chlorine:connect-socket-repl (input.hidden-input)
     -1:16.7.0 core:focus-next (input.input-text)
     -1:10.5.0 editor:newline (input.hidden-input)
     -1:09.0 core:move-down (input.hidden-input)
     -0:51.2.0 chlorine:rebl-top-block (input.hidden-input)
     -0:36.5.0 editor:newline (input.hidden-input)
     -0:34.8.0 core:backspace (input.hidden-input)
     -0:25.4.0 chlorine:rebl-top-block (input.hidden-input)
     -0:18.3.0 chlorine:clear-console (input.hidden-input)
     -0:15.9.0 chlorine:disconnect (input.hidden-input)
```

### Non-Core Packages

```
chlorine 0.9.4 
```

**Comment by mauricioszabo** [comment]
Fixed on 0.10.2
