### ISSUE TITLE
Uncaught Error: G__5 is not ISeqable after inline evaluation

### ISSUE THREAD

**Issue by gustavobertolino** [mauricioszabo/atom-chlorine#232]
[Enter steps to reproduce:]

1. In a terminal, build the cljs application with hot-reloading running `shadow-cljs watch <app>`, where <app> is the alias for the main function to be found by cljs compiler and contained in .edn file. 
2. In other terminal, fire REPL with lumo on port 3322 running `lumo -n 3322`
3. Connect to this REPL running Chlorine command socket connect
3. Load the namespace with inline evaluation command
4. Try to load a print hello-world function with inline evaluation command

The problematic inline evaluation keep running and a error message is thrown on the screen
![Screenshot from 2021-01-18 17-51-22](https://user-images.githubusercontent.com/25723294/104961874-05bb1a00-59b6-11eb-8bcc-cc7ccb928c69.png)

**Atom**: 1.49.0 x64
**Electron**: 5.0.13
**OS**: Ubuntu 18.04.5
**Thrown From**: [chlorine](https://github.com/mauricioszabo/atom-chlorine) package 0.10.2

### Stack Trace

Uncaught Error: G__5 is not ISeqable

```
At /home/gbertolino/.atom/packages/chlorine/lib/cmds.js:526

Error: G__5 is not ISeqable
    at /packages/chlorine/lib/cmds.js:526:275)
    at k.h.da (/packages/chlorine/lib/cmds.js:879:78)
    at td (/packages/chlorine/lib/cmds.js:467:289)
    at Function.eg.g (/packages/chlorine/lib/cmds.js:545:393)
    at /packages/chlorine/lib/cmds.js:968:349
    at Function.Lf.G (/packages/chlorine/lib/cmds.js:535:223)
    at cd.h.kb (/packages/chlorine/lib/cmds.js:540:30)
    at Function.jd.g (/packages/chlorine/lib/cmds.js:585:289)
    at Function.jn.j (/packages/chlorine/lib/cmds.js:968:323)
    at /packages/chlorine/lib/cmds.js:2867:435
    at ROa (/packages/chlorine/lib/cmds.js:2830:427)
    at /packages/chlorine/lib/cmds.js:2831:218
    at NOa (/packages/chlorine/lib/cmds.js:2826:534)
    at POa (/packages/chlorine/lib/cmds.js:2828:329)
    at /packages/chlorine/lib/cmds.js:2828:474
    at pk.h.Ge (/packages/chlorine/lib/cmds.js:723:431)
    at vk (/packages/chlorine/lib/cmds.js:725:348)
    at Function.xk.h (/packages/chlorine/lib/cmds.js:728:206)
    at /packages/chlorine/lib/cmds.js:2832:227)
    at Socket.emit (events.js:194:13)
    at addChunk (_stream_readable.js:296:12)
    at readableAddChunk (_stream_readable.js:277:11)
    at Socket.Readable.push (_stream_readable.js:232:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:165:17)
```

### Commands

```
     -1:23.3.0 x-terminal:open-split-right-context-menu (div.title.icon.icon-terminal)
     -1:12 x-terminal:paste (textarea.xterm-helper-textarea)
     -1:05.3.0 command-palette:toggle (input.hidden-input)
  2x -0:58.8.0 core:move-down (input.hidden-input)
     -0:57.4.0 core:confirm (input.hidden-input)
     -0:57.4.0 chlorine:connect-socket-repl (input.hidden-input)
     -0:45.3.0 x-terminal:copy (textarea.xterm-helper-textarea)
     -0:29.8.0 settings-view:open (input.hidden-input)
  2x -0:22.3.0 chlorine:evaluate-block (input.hidden-input)
```

### Non-Core Packages

```
atom-elixir 0.2.3 
atom-slime 2.8.0 
autocomplete-erlang 1.1.2 
chlorine 0.10.2 
dash 1.7.1 
ink 0.10.2 
language-common-lisp 0.9.5 
language-elixir 0.24.0 
language-erlang 3.2.0 
language-lisp 0.2.0 
linter-slime-lint 0.3.1 
lisp-paredit 0.8.0 
parinfer 1.24.1 
platformio-ide-terminal 2.10.1 
proto-repl 1.4.24 
proto-repl-charts 0.4.1 
proto-repl-sayid 0.1.4 
slima 2.7.0 
terminus 4.1.1 
x-terminal 12.1.0 
```

**Comment by mauricioszabo** [comment]
Ok, this is mostly a problem with Lumo and Chlorine. I'll address this, in the meantime you can disable pretty-printing on Lumo by issuing the command: `(set! lumo.repl/*pprint-results* false)`

Then this bug goes away. Just out of curiosity, why are you using Lumo *and* shadow-cljs?

**Comment by gustavobertolino** [comment]
I see, Mauricio. I'm using Lumo because just connecting to the nREPL fired by shadow-cljs build doesn't work in my Atom editor. I tried following the instructions below from the Chlorine, but it still doesn't work properly

![image](https://user-images.githubusercontent.com/25723294/104963446-541de800-59b9-11eb-879a-88570b1abb1e.png)

**Comment by gustavobertolino** [comment]
Specially the last command "Connect Embedded" doesn't seem generating any effect on the editor or the REPL fired.

**Comment by gustavobertolino** [comment]
Other strange thing is the modal window to insert localhost and the port number. I can simply paste any values on these fields, but I cannot type any character or numbers on them

![Screenshot from 2021-01-18 18-21-38](https://user-images.githubusercontent.com/25723294/104964251-cfcc6480-59ba-11eb-9a82-b49d44aa5697.png)
.

**Comment by mauricioszabo** [comment]
Ok, there are multiple strange things here:

First, when you `watch` a project, Chlorine will add the Shadow-CLJS' port for you. Are you not seeing it happening? Also, you don't connect into a "shadow-cljs nREPL" - by default, it connects into a socket-repl (with the auto-detected port)...

Another thing, the port will try to convert your text into numbers. I'm not aware of any problems or issues regarding it...

**Comment by gustavobertolino** [comment]
Just to update this issue, Mauricio

It doesn't appear any information that this port is added automatically. The modal window to include host and port just appears and I thought that I have to insert the same port of the repl fired by the shadow-cljs.

I enabled the "experimental features" in the Chlorine's settings, as you suggested in other Clojure forum, and it works well doing the following:

1. shadow watch
2. connect socket repl
3. connect embedded

It means not using neither firing lumo repl during these steps. 

Well, I got my problem fixed, but I'm not sure if the combination shadow-cljs + lumo is a good fit or if they simply shouldn't be combined on Chlorine. If it's the last option, I think the issue is closed.

**Comment by mauricioszabo** [comment]
Shadow-CLJS + Lumo is not a valid fit for any kind of workflow, but the bug still exist - Lumo is not working right now, so I'll keep this issue open (even if no-one uses Lumo, it's still good to have it on Chlorine)

**Comment by mauricioszabo** [comment]
Fixed :)
