### ISSUE TITLE
Autocomplete error when disconnected

### ISSUE THREAD

**Issue by mauricioszabo** [mauricioszabo/atom-chlorine#26]
1. Connect to a socket REPL
2. Disconnect
3. Try to auto-complete anything

`Uncaught TypeError: Cannot read property 'then' of null`

### Stack Trace
```
At /home/mauricio/.atom/packages/chlorine/lib/js/cljs-runtime/chlorine.providers_consumers.autocomplete.js:71

TypeError: Cannot read property 'then' of null
    at /packages/chlorine/lib/js/cljs-runtime/chlorine.providers_consumers.autocomplete.js:71:40)
    at /packages/chlorine/lib/js/cljs-runtime/chlorine.providers_consumers.autocomplete.js:81:122
    at Object.getSuggestions (/packages/chlorine/lib/js/cljs-runtime/chlorine.providers_consumers.autocomplete.js:82:3)
    at providers.forEach.provider (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:309:58)
    at Array.forEach (<anonymous>)
    at AutocompleteManager.getSuggestionsFromProviders (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:280:21)
    at AutocompleteManager.findSuggestions (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:272:23)
    at HTMLElement.autocomplete-plus:activate (/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:245:20)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
     -2:46.8.0 vim-mode-plus:move-up (input.hidden-input)
     -1:49.1.0 everything:fuzzy-finder (input.hidden-input)
     -1:47.7.0 core:confirm (input.hidden-input)
     -1:47.7.0 chlorine:disconnect (input.hidden-input)
     -1:46.9.0 vim-mode-plus:insert-after-end-of-line (input.hidden-input)
     -1:46.6.0 lisp-paredit:newline (input.hidden-input)
     -1:45.7.0 autocomplete-plus:activate (input.hidden-input)
     -1:30.3.0 everything:fuzzy-finder (input.hidden-input)
     -1:28.5.0 core:confirm (input.hidden-input)
     -1:28.5.0 chlorine:connect-clojure-socket-repl (input.hidden-input)
     -1:26.6.0 editor:focus (input.hidden-input)
     -1:26.6.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -1:25.7.0 editor:delete-to-beginning-of-word (input.hidden-input)
  4x -1:25.4.0 core:backspace (input.hidden-input)
     -1:23.9.0 autocomplete-plus:activate (input.hidden-input)
     -1:22.8.0 autocomplete-plus:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
parinfer-plus 0.0.0 
chlorine 0.0.6 
clojure-plus 0.3.0 
everything 0.3.1 
ex-mode 0.18.0 
hard-wrap 1.7.1 
hey-pane 1.1.2 
ink 0.9.12 
language-ansi 1.1.1 
language-haml 0.31.1 
language-scala 1.1.9 
last-cursor-position 0.9.3 
linter 2.2.0 
linter-ui-default 1.7.1 
lisp-paredit 0.6.0 
parinfer 1.23.0 
proto-repl 1.4.24 
set-syntax 0.4.0 
simple-align 0.2.0 
simple-git 0.2.0 
sync-settings 0.8.6 
Termrk 1.0.1 
tmux-terminal 0.0.1 
vim-mode-plus 1.34.0 
```

**Comment by seancorfield** [comment]
Did this get into 0.0.7?

**Comment by mauricioszabo** [comment]
Will be on 0.0.8
